package com.oudmaijer.drools

import com.oudmaijer.drools.fraud.model.*

global Errors errors

rule "Order has orderId"
    when
        $order : Order( orderId == null )
    then
        errors.add("Order.orderId empty: "+ $order);
end

rule "Order has orderItems"
    when
        $order : Order( orderItems != null, orderItems.empty == true )
    then
        errors.add("Order.orderItems empty: "+ $order);
end