package com.oudmaijer.drools

import com.oudmaijer.drools.fraud.model.*
import java.util.List

global Errors errors

rule "Seller shipment address on blacklist"
    when
        Blacklist($addressBlacklist : addresses)

        $order : Order( shipmentAddress memberOf $addressBlacklist,     // blacklist rule
                        paymentType != "02" )                           // whitelist rule
    then
        errors.add("Seller shipment address on blacklist and not in allowed paymentType: "+ $order);
end
